# THIS SHOULD BE IN SYNC W/ RPI AND LAPTOP
# ALIAS BLOCK START
alias ll='ls -alF'
alias la='ls -A'
alias lo='ls --sort=time'
alias l='ls -lF --sort=time'
alias watch='watch --color -n1'
alias grep='grep --color'
alias agi='sudo apt-get install'
alias agr='sudo apt-get remove'
alias py2='python2'
alias py3='python3'
alias s='sudo'
alias create-readme='cp $HOME/.README.md ./README.md && vim README.md'
alias r='ranger --choosedir=$HOME/.rangerdir --cmd="set preview_files=true" "$(if [ -z "$@" ]; then cat $HOME/.rangerdir; fi)";cd "`cat $HOME/.rangerdir`"'
alias sr='sudo ranger --choosedir=$HOME/.rangerdir --cmd="set preview_files=true" "$(if [ -z "$@" ]; then cat $HOME/.rangerdir; fi)"|lolcat-c;cd "`cat $HOME/.rangerdir`"'
alias v='vim'
# test .Xdefaults colors
alias testx='echo;for a in {40..47}; do echo -ne "\e[0;30;$a""m  ""\e[0;37;39m "; done; echo ""'
alias cutefetch='while true; do screenfetch_out="$(screenfetch -a $HOME/nexor.ascii -p)$(testx;echo;echo;echo)";clear;printf "$screenfetch_out"|lolcat-c;sleep 0.01; done'
alias neofetch="screenfetch -a $HOME/nexor.ascii -p"
alias vmutt='sudo vim $HOME/.muttrc'
alias vvrc='sudo vim $HOME/.vimrc'
alias vr='sudo vim $HOME/.config/ranger'
alias gc='git clone'
alias vp='vim "$HOME/Dropbox/Sys4Bank - Programas Java/pendencias.txt"'
alias sv='sudo vim'
alias vtmux='vim $HOME/.tmux.conf'
alias srm='sudo rm'
alias find='sudo find'
alias mkdir='mkdir -p'
# terminal geographic map
alias termap='telnet mapscii.me'
# tmux attach
alias ta='tmux a -t sess0'
alias smv='sudo mv'
alias msk='ncmpcpp'
alias vxdef='sudo vim $HOME/.Xdefaults'
# config bashrc
alias cfb='sudo vim $HOME/.bashrc'
# config this
alias cfa='sudo vim $HOME/.bash_aliases'
# config dotfiles
alias cfd='sudo vim $HOME/disk/gdrive/Programming/bash/dotfiles/grab_updated_and_push.sh'
# config push
alias cfp='. $HOME/disk/gdrive/Programming/bash/dotfiles/grab_updated_and_push.sh'
alias motd='sudo cat /etc/update-motd.d/nexor.asc'
alias serve='python3 -m http.server 2717'
alias schmod='sudo chmod'
alias snode='sudo node'
alias sf='sudo find / -iname'
alias weather='curl wttr.in'
alias h='cd ..'
alias eye='tail -f'
alias ka='killall'
alias e='echo'
alias c='xsel -i -b'
alias feh='feh --sort mtime'
alias cal='calcurse'
alias randip="dd if=/dev/urandom bs=4 count=1 2>/dev/null | od -An -tu1 | sed -e 's/^ *//' -e 's/  */./g'"
alias mp42wmv='sudo ffmpeg -c:v wmv2 -b:v 99M -c:a wmav2 -b:a 192k output.wmv -i'
alias o='xdg-open'
alias g='grep'
alias it='ps aux|head -n -1|grep '
alias prolog='swipl -q'
alias t='date +%s'
alias rsync='rsync -a --info=progress2'
# open in existing browser window
alias waterfox='[[ $(ps aux|grep -c waterfox) -eq 1 ]] && waterfox || waterfox -new-tab'
alias R='R --silent '
# alias mp42gif='mp4_file="$@"; mkdir -p animation_frames; ffmpeg -i "$mp4_file" -r 5 "animation_frames/frame-%03d.jpg"; convert -delay 20 -loop 0 animation_frames/*.jpg animation.gif; rm -r animation_frames'
alias acs='apt-cache search'
alias lisp='clisp --silent'
alias pa='ps aux|grep'
alias jsonify='python -m json.tool'
alias iftop='sudo iftop -Nlp'
alias cava='cava -p $HOME/.config/cava/config'
alias usdbrl='curl "http://free.currencyconverterapi.com/api/v5/convert?q=USD_BRL&compact=y" 2>&1 | re "\:(\d[^}]+)}" | e R\$ $(cat -)'
alias eurbrl='curl "http://free.currencyconverterapi.com/api/v5/convert?q=EUR_BRL&compact=y" 2>&1 | regextract "\:(\d[^}]+)}" | e R\$ $(cat -)'
alias btcbrl='curl "http://free.currencyconverterapi.com/api/v5/convert?q=BTC_BRL&compact=y" 2>&1 | regextract "\:(\d[^}]+)}" | e R\$ $(cat -)'
alias ali='apt list --installed'
alias alsao2i='pacmd set-default-source "alsa_output.pci-0000_00_1b.0.analog-stereo.monitor"'
alias alsai2i='pacmd set-default-source "alsa_input.pci-0000_00_1b.0.analog-stereo"'
alias alsawat='pacmd list-sources|grep -A 5 \* '
alias giquo='regextract "\"([^\"]+)"'
alias gipar='regextract "\(([^\)]+)"'
alias gip='regextract "((\d{1,3}\.){3}\d{1,3})"'
# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
#   text to speech:
function tts(){ printf "(SayText \"$1\")" | festival -i;}
