#!/bin/bash
kek=$(wmctrl -l -p | grep "$(ps aux | grep nemo | ack '^nexor\s+(\S+).*\snemo\s' --output='$1')" | ack '^(\S+)' --output='$1')
echo $kek
#wid=$(echo $kek | ack '^nexor\s+(\S+).*\snemo\s' --output='$1')
echo $wid
#if [[ -n $wid ]]; then
#    wmctrl -a $wid;
#fi

