#!/bin/bash
ytlink="$1"
echo -n "Name of new wallpaper: "
read name
cd /System/Resources/Komorebi/
sudo cp -r lava $name
cd $name
rm *.wmv
sudo youtube-dl "$1"
sudo rm wallpaper.jpg
sudo ffmpeg -i *.mp4 -r 0.0033 -vf scale=-1:120 -vcodec png wallpaper.png
convert wallpaper.png wallpaper.jpg
rm wallpaper.png
sudo ffmpeg -c:v wmv2 -b:v 99M -c:a wmav2 -b:a 192k output.wmv -i *.mp4
sudo rm *.mp4
