#!/bin/bash
myclipfolder="$HOME/.myclip/fscb"
if test "$(ls -A $myclipfolder 2>/dev/null)"; then
    if [ "$1" ]; then 
        mv "$myclipfolder/*" "$1"
    else
        echo kek
        curdir=`pwd`
        mv "$myclipfolder"/* "$curdir"
    fi
else 
    mv "$1" $myclipfolder
fi
