#!/usr/bin/python3
import re
import sys
import fileinput

content=''
for l in sys.stdin: content+=l
regex = sys.argv[1]
search=re.findall(regex,content)
for result in search:
    print(search.group(sys.argv[2] if len(sys.argv)>2 else 1))
else: print('No matches')
